# Liquibase Configuration
changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://db:5432/economic_indicators
username=postgres
password=postgres
driver=org.postgresql.Driver
liquibase.hub.mode=off
